apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-pod-sa
  annotations:
    eks.amazonaws.com/role-arn: ROLE_ARN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      serviceAccountName: my-pod-sa
      containers:
        - name: my-pod
          image: amazon/aws-cli:latest
          command:
            - "sh"
            - "-c"
          args:
            - "tail -f /dev/null"
