apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-pod-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/test-pod-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: my-pod-sa
      containers:
        - name: my-pod
          image: amazon/aws-cli:latest
          command:
            - "sh"
            - "-c"
          args:
            - "tail -f /dev/null"
